### ISSUE TITLE
Invert colors

### ISSUE THREAD

**Issue by DONSA** [kimar/DeveloperExcuses#15]
Is it possible to invert the colors?

**Comment by kimar** [comment]
This is currentlt hard-coded inside the OnelinerKit Framework (https://github.com/kimar/OnelinerKit/blob/master/OnelinerKit/View/OnelinerView.swift#L53) but I think it would make sense to abstract this in the framework and implement Settings in the ScreenSaver.

**Comment by kimar** [comment]
I have implemented a way to alter colors in OnelinerKit, now the next step would be to properly implement this in DeveloperExcuses, here's an example with two different, hardcoded, colors: https://github.com/kimar/DeveloperExcuses/tree/colorsExample
<img width="1048" alt="bildschirmfoto 2018-08-08 um 21 37 54" src="https://user-images.githubusercontent.com/126418/43860413-ecf2fc18-9b53-11e8-8c0d-1f05f626ce58.png">

**Comment by DONSA** [comment]
Never did anything with Swift. How can I compile it?

**Comment by DONSA** [comment]
I did those changes, hit Build and then replace current screen saver with compiled version in:
`Library⁩ ▸ ⁨Developer⁩ ▸ ⁨Xcode⁩ ▸ ⁨DerivedData⁩ ▸ ⁨DeveloperExcuses-fxfzocpddjkyofbcqccparpelguv⁩ ▸ DeveloperExcuses.saver`
Still no changes. I'm I doing something wrong?

**Comment by kimar** [comment]
Can you try uninstalling the currently installed one first? (Using `Settings -> Screensaver`). Might be cached. Usually the changes should show up, did you check everything looks correct using the build in Debug View?

**Comment by DONSA** [comment]
I tried to uninstall it first but still no luck. No compile errors that I'm aware of.
